nodeLinker: node-modules

npmScopes:
  leagueakari:
    npmAuthToken: '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'
    npmRegistryServer: 'https://npm.pkg.github.com'
  leaguetavern:
    npmAuthToken: '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'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.9.1.cjs
